language: ruby
before_install:
  # install a newer cmake since at this time Travis only has version 2.8.7
  - yes | sudo add-apt-repository ppa:kalakris/cmake
  - sudo apt-get update -qq
install: sudo apt-get update -qq
rvm:
  - 1.9.3
  - 2.0.0
  - ruby-head
